# Generated by Django 5.1.2 on 2025-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NOTAM_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('notam_text', models.TextField()),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('start_hour', models.CharField(blank=True, max_length=4, null=True)),
                ('end_date', models.DateField()),
                ('end_hour', models.CharField(blank=True, max_length=4, null=True)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('series', 'number', 'year')},
            },
        ),
    ]
