# Generated by Django 5.1.2 on 2025-02-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrpw_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_model',
            name='end_date',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='notam_model',
            name='start_date',
            field=models.CharField(max_length=6),
        ),
    ]
