# Generated by Django 5.1.4 on 2025-02-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrpw_website', '0003_alter_notam_model_options_remove_notam_model_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notam_model',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notam_model',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacing_notams', to='lrpw_website.notam_model'),
        ),
    ]
