# Generated by Django 5.1.4 on 2025-02-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrpw_website', '0004_notam_model_replaced_notam_model_replaced_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notam_model',
            old_name='notam_text',
            new_name='notam_RAW_text',
        ),
    ]
