# Generated by Django 5.1.2 on 2025-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrpw_website', '0006_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='feels_like',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='absolute_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='indoor_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='indoor_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='outdoor_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='outdoor_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='relative_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
